<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcVkp10\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcVkp10/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQcVkp10.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQcVkp10\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQcVkp10\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QcVkp10',
    'container.build_id' => 'd10fd234',
    'container.build_time' => 1763629524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcVkp10');
