<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ2I3aqp\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ2I3aqp/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ2I3aqp.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ2I3aqp\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQ2I3aqp\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Q2I3aqp',
    'container.build_id' => 'd0b05f6e',
    'container.build_time' => 1765732591,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ2I3aqp');
